# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='number',
            field=models.IntegerField(),
        ),
    ]
