# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_station_stop_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='date',
            field=models.DateField(),
        ),
    ]
