# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20160411_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllSeatClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('3AC', '3A'), ('2AC', '2A'), ('SL', 'Sleeper')], max_length=3)),
                ('available_seat', models.IntegerField(default=10)),
            ],
        ),
        migrations.AddField(
            model_name='allseatclass',
            name='second_ac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_ac', to='booking.Seat'),
        ),
        migrations.AddField(
            model_name='allseatclass',
            name='sleeper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleeper', to='booking.Seat'),
        ),
        migrations.AddField(
            model_name='allseatclass',
            name='third_ac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_ac', to='booking.Seat'),
        ),
        migrations.AddField(
            model_name='train',
            name='seat',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='booking.AllSeatClass'),
        ),
    ]
