# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20160412_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allseatclass',
            name='second_ac',
        ),
        migrations.RemoveField(
            model_name='allseatclass',
            name='sleeper',
        ),
        migrations.RemoveField(
            model_name='allseatclass',
            name='third_ac',
        ),
        migrations.RemoveField(
            model_name='train',
            name='seat',
        ),
        migrations.AddField(
            model_name='train',
            name='second_ac',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_ac', to='booking.Seat'),
        ),
        migrations.AddField(
            model_name='train',
            name='sleeper',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='sleeper', to='booking.Seat'),
        ),
        migrations.AddField(
            model_name='train',
            name='third_ac',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_ac', to='booking.Seat'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='available_seat',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.DeleteModel(
            name='AllSeatClass',
        ),
    ]
