# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_ticket_train'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Train'),
        ),
    ]
